name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  json_annotation: ^4.8.0
  dio: ^5.0.0
  flutter:
    sdk: flutter
  appinio_swiper: ^1.1.1
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.9
  flutter_feather_icons: ^2.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  hive_generator: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
